### ISSUE TITLE
Hide Trailing Item

### ISSUE THREAD

**Issue by EdwardArr** [markvanwijnen/NavigationBarLargeTitleItems#2]
Trailing item from navigation bar appears when navigating to another screen in a navigation view. Does anyone know how to disappear this view when navigation to another screen?

**Comment by moh-abk** [comment]
this gave me the desired outcome;

```
override func viewWillDisappear(_ animated: Bool) {
    guard let navigationBar = self.navigationController?.navigationBar else {
        return
    }

    guard let UINavigationBarLargeTitleView = NSClassFromString("_UINavigationBarLargeTitleView") else {
        return
    }

    navigationBar.subviews.forEach {
        subview in
        if subview.isKind(of: UINavigationBarLargeTitleView.self) {
            subview.alpha = 0
        }
    }
}
```

**Comment by EdwardArr** [comment]
Unfortunately the code didn't work. To give a bit more context, the subview is using a navigation bar with large display mode.

**Comment by moh-abk** [comment]
Weird it fixed it for me when using NavigationLink the icons no longer show up on the navigated screen for a second which is the bug 🐛 you’re seeing
